version: "3.0"

services:
  redis:
    image: redis:alpine
  dancer:
    image: hectorvido/dancer
    environment:
    - "REDIS_SERVER=redis"
    - "REDIS_PORT=6379"
    depends_on:
    - redis
    ports:
    - 5000:5000
